version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: water-quality-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '1111'
      MYSQL_DATABASE: 'water_quality_db'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: